openvswitch: Fix openvswitch with dpdk do_configure failed
Issue: LINCD-4767

Fix follow error:
"DEBUG:	| checking whether linking with dpdk works... no
| checking whether linking with dpdk works... no
DEBUG:	| configure: error: Could not find DPDK library
in default search path, update PKG_CONFIG_PATH for pkg-config
to find the .pc file in non-standard location
| configure: error: Could not find DPDK library in default
search path, update PKG_CONFIG_PATH for pkg-config to find
the .pc file in non-standard location"

The "0001-openvswitch-fix-do_configure-with-DPDK*.patch"
fix do_cofigure error converted to warning when
check pkg-config version mismatch.

The "0001-openvswitch-fix-netdev-dpdk-compile*.patch" fix
compilation error of the definition of function between
different DPDK versions.

(LOCAL REV: NOT UPSTREAM) -- Wind River specific

Signed-off-by: Zqiang <qiang.zhang@windriver.com>