conf/layer.conf: Add meta-python to LAYERDEPENDS
Issue: LIN10-5736

python3-dockerpty requires pypi.bbclass which is in meta-python.

Fixed when update meta-virtualization in layerindex:
$ update.py -b WRLINUX_10_17_BASE -l meta-virtualization --reload

FileNotFoundError: [Errno 2] file classes/pypi.bbclass not found

(LOCAL REV: NOT UPSTREAM) -- Upstream already fixed it

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>