openvswitch: getVar() requires 2 args in older bitbake
Since we are using older bitbake on LIN9 we need to supply the second
arg to getVar() or we will get:

TypeError: getVar() missing 1 required positional argument: 'expand'

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>